name: rec-sys
channels:
    - defaults
    - pytorch
    - conda-forge
dependencies:
    - seaborn
    - matplotlib
    - numpy=1.21
    - pandas
    - jupyterlab
    - scikit-learn
    - django
    - django-allauth
    - pymysql
    - mysql-connector-python
    - pip
    - pip:
        - --extra-index-url https://download.pytorch.org/whl/cu116
        - torch==1.12.1+cu116
        - torchvision==0.13.1+cu116