# Generated by Django 4.1 on 2023-08-16 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recsysweb', '0055_alter_recommender_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommender',
            name='max_items_by_similar_user',
            field=models.IntegerField(default=20, verbose_name='Max Items by Similar Users'),
        ),
        migrations.AlterField(
            model_name='recommender',
            name='max_similar_items',
            field=models.IntegerField(default=50, verbose_name='Max Similar Items'),
        ),
        migrations.AlterField(
            model_name='recommender',
            name='max_similar_users',
            field=models.IntegerField(default=10, verbose_name='Max Similar Users'),
        ),
    ]
