# Generated by Django 4.1 on 2023-09-12 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recsysweb', '0057_auto_20230912_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='rating',
            field=models.FloatField(verbose_name='Rating'),
        ),
        migrations.AlterField(
            model_name='similaritymatrix',
            name='type',
            field=models.IntegerField(choices=[(1, 'User To User'), (2, 'Item To Item')], default=1, verbose_name='Similarity Matrix Type'),
        ),
        migrations.AlterField(
            model_name='similaritymatrix',
            name='version',
            field=models.IntegerField(default=0, verbose_name='Version'),
        ),
        migrations.AlterField(
            model_name='similaritymatrixcell',
            name='value',
            field=models.FloatField(verbose_name='Value'),
        ),
        migrations.AlterField(
            model_name='similaritymatrixcell',
            name='version',
            field=models.IntegerField(default=0, verbose_name='Version'),
        ),
    ]
